### ISSUE TITLE
Incorrectly show coordinate axis of SequnceTube and annotation data

### ISSUE THREAD

**Issue by hahahafeifeifei** [MoMI-G/MoMI-G#90]
Hi, I'm trying to load my data to MoMI-G.

The `vg` file is converted from `rgfa` (minigraph) file. And `xg` file is generated using `vg index`. There is no problem visualizing the `xg` file on SequenceTubeMap (vgteam).
![image](https://user-images.githubusercontent.com/36079508/146422004-b197f4a2-aafe-4b52-86c2-d2f63248f7e1.png)

But when I loaded the `xg` file to MoMI-G, some problems arose. The coordinate axis of SequnceTubeMap is disordered and it's unable to show the annotation data on the website.
![image](https://user-images.githubusercontent.com/36079508/146423787-63cba05e-5ef0-4bb6-a109-07251848655c.png)
![image](https://user-images.githubusercontent.com/36079508/146423816-b6396cb7-b1ae-45bf-8cb8-0ca58110dd16.png)

Additionally, the same problem arose when I converted the example data `chm1_chr21.pcf` to `xg` file using vg (v1.14.0):
```
pcf2gfa.sh chm1_chr21.pcf hg38_chr1.fa > chm1_chr21.gfa
vg view -Fv chm1_chr21.gfa > chm1_chr21.old.vg
vg mod -X 1024  chm1_chr21.old.vg >  chm1_chr21.vg
vg index -x  chm1_chr21.xg  chm1_chr21.vg
```
I checked the errors. It indicated that some wrong happens around GraphWrapper.tsx:
![image](https://user-images.githubusercontent.com/36079508/146424213-9fe97d44-096e-4882-b8a6-d54b874bcf4b.png)
And it seems that the cause of the problems is unable to resolve the coordinate information in `xg` file.
![image](https://user-images.githubusercontent.com/36079508/146424291-1da87714-4578-46c4-a118-acf171f82648.png)

Could you please help me with my problems?
Thanks!

**Comment by 6br** [comment]
Thank you for using MoMI-G. I fixed the error "Cannot convert undefined or null to object" in the latest master.
For the incorrect coordinate issue, our development team is currently investigating this. Would it be possible for you to wait for a while?

**Comment by 6br** [comment]
I cannot reproduce the incorrect coordinate issue (in vg 1.23).

<img width="1654" alt="2021-12-21 0 40 52" src="https://user-images.githubusercontent.com/12047794/146864854-b9228c0c-c8bd-499e-83c1-6c6ead2ca129.png">
 
In this case, the coordinates of `chr21` is displayed in the ruler, and those of other paths are not displayed. When the name of the main path is too long, MoMI-G recognizes the path is not chromosome; thus, the coordinates are not displayed.

**Comment by hahahafeifeifei** [comment]
Thanks for your prompt reply! It's very strange that this problem can't be reproduced.

I cloned the last master of MoMI-G and tried again. I used the `pcf2gfa.sh` (the last master) and `vg` (v1.23.0) to convert `chm1_chr21.pcf` to `xg` file:
```
#reference genome is chromosome 21 of hg38
pcf2gfa.sh chm1_chr21.pcf hg38_chr21.fa > chm1_chr21.gfa
vg view -Fv chm1_chr21.gfa > chm1_chr21.old.vg
vg mod -X 1024  chm1_chr21.old.vg >  chm1_chr21.vg
vg index -x  chm1_chr21.xg  chm1_chr21.vg
```

This is the configuration file of docker I used:
```
FROM quay.io/vgteam/vg:v1.23.0 as build
# frontend container
FROM momigteam/momig-backend:latest

COPY --from=build /vg/bin/vg /vg/bin/
COPY static/chm1_chr21.xg /vg/static/
COPY static/config.yaml /vg/static/
EXPOSE 8081

CMD ["./graph-genome-browser-backend", "--config=static/config.yaml", "--interval=1500000", "--http=0.0.0.0:8081", "--api=/api/v2/"]
```

This is the configuration file of MoMI-G I used:
```
bin:
  vg: "vg"
  vg_tmp: "vg"
  vg_volume_prefix: ""
  graphviz: "dot"
  fa22bit: "faToTwoBit"
  bigbed: "bedToBigBed"
reference:
  chroms: "static/GRCh.json"
  data:
    - name: "hg38"
      features:
        - name: "gene_annotation"
          url: "static/gencode.v27.basic.annotation.gff3"
          chr_prefix: "chr"
data:
  - name: "chm1"
    desc: "2017/12/18"
    chr_prefix: "chr"
    ref_id: "hg38"
    source:
      xg: "/vg/static/chm1_chr21.xg"
      csv: "static/chm1_chr21.pcf"
    features:
      - name: "gene_annotation"
        url: "static/ensGene.bb"
        chr_prefix: "chr"
    static_files: []
```
But the incorrect coordinate issue still exists.
![image](https://user-images.githubusercontent.com/36079508/146886631-46ef5174-a816-44ae-af27-e2306e228b0f.png)
![image](https://user-images.githubusercontent.com/36079508/146888882-f0e0a8d1-edc9-42a5-b3f0-deed3f434954.png)

I'm wondering what commands you used to make `xg` file. And this is my `xg` file, you can download and test it.
https://www.dropbox.com/s/k217q15o03ro5gl/chm1_chr21.xg?dl=0

**Comment by 6br** [comment]
Thank you for sharing the detail. The configuration seems good to me. Is it possible to tell me the genomic range of the incorrect coordinate so that I can see the same view?
<img width="1631" alt="2021-12-21 18 06 21" src="https://user-images.githubusercontent.com/12047794/146902591-38653e48-9f15-4919-b3f8-ee9d26f60b2b.png">

**Comment by hahahafeifeifei** [comment]
The genomic range: chr21:45,839,448-46,840,448

**Comment by 6br** [comment]
Still I failed to reproduce the same view.
Is it possible to use ` momigteam/momig-backend:prod` instead of `momigteam/momig-backend:latest`?
Is the frontend running the latest master of MoMI-G?

**Comment by 6br** [comment]
This is my chm1 chr21 xg file.
https://www.dropbox.com/s/g9je846z0aka54x/chm1_chr21.xg?dl=0

**Comment by hahahafeifeifei** [comment]
I used `momigteam/momig-backend:prod` and it worked!
![image](https://user-images.githubusercontent.com/36079508/146954232-b27231d6-9174-459b-9caa-99d519e3e4e7.png)

Although annotation path can be shown in SequenceTubeMap, an error occurred:
```
[2021-12-21T14:40:13Z DEBUG graph_genome_browser_backend::annotations] Unsupported format "static/ensGene.bed"
```
And why does annotation path miss as the genome range becomes longer?

Additionally, if I want to use MoMI-G without using Docker, which softwares should I install?

**Comment by 6br** [comment]
1. annotation path can be shown in SequenceTubeMap, an error occurred: `Unsupported format "static/ensGene.bed"`

Please use bigbed file instead of bed file.

```
    features:
      - name: "gene_annotation"
        url: "static/ensGene.bb"
        chr_prefix: "chr"
```


2. And why does annotation path miss as the genome range becomes longer?

<img width="1680" alt="2021-12-22 16 28 09" src="https://user-images.githubusercontent.com/12047794/147062405-7df8d40f-c1ee-4576-b4ba-e5d797d439e6.png">


This might be a bug, I fixed in #93. If annotation paths are still missing, please tell me.

3. Additionally, if I want to use MoMI-G without using Docker, which softwares should I install?

[MoMI-G backend](https://github.com/MoMI-G/MoMI-G_backend ) is available on GitHub. See Dockerfile to run MoMI-G backend: https://github.com/MoMI-G/MoMI-G_backend/blob/master/Dockerfile

**Comment by hahahafeifeifei** [comment]
MoMI-G works perfectly now!
![image](https://user-images.githubusercontent.com/36079508/147116526-8fccb11d-7a98-4e46-854f-5bf28b6fa401.png)
Thank you so much for your help!

**Comment by 6br** [comment]
Awesome! Please contact us if you have any questions.
